/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\mymodel.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mymodel.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.293, -1.237, 6.854]} rotation={[0.087, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['Material.004']} />
      </group>
      <group position={[0.295, 8.541, -6.856]} rotation={[-1.745, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials['Material.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/mymodel.glb')
