/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Laptop.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/Laptop.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="ScreenFace" geometry={nodes.ScreenFace.geometry} material={materials['Material.003']} position={[17.213, 50.1, -2.076]} rotation={[0, -1.571, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Laptop.glb')
